In [2]:
import pandas as pd
import json

Process Match Result

In [3]:
with open(r'D:\Deepak_Work\Our Goal is Google\Cricket_data_analysis\t20_json_files\t20_json_files\t20_wc_match_results.json') as f:
    data = json.load(f)
# len(data) # Data array has only one element.
df_match= pd.DataFrame(data[0]['matchSummary'])
df_match.head()

,team1,team2,winner,margin,ground,matchDate,scorecard
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [4]:
df_match.shape

(45, 7)

In [5]:
df_match.rename({'scorecard':'match_id'}, axis = 1, inplace = True)

df_match.head()

,team1,team2,winner,margin,ground,matchDate,match_id
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [6]:
match_ids_dict = {}
for index, row in df_match.iterrows():
    key1 = row['team1'] + ' Vs ' + row['team2']
    key2 = row['team2'] + ' Vs ' + row['team1']

    match_ids_dict[key1] = row['match_id']
    match_ids_dict[key2] = row['match_id']

In [7]:
df_match.to_csv('t20_csv_files/dim_match_result.csv', index = False)

"Batting Score"

In [8]:
with open(r'D:\Deepak_Work\Our Goal is Google\Cricket_data_analysis\t20_json_files\t20_json_files\t20_wc_batting_summary.json') as f:
    data = json.load(f)
    
    all_records = []
    for rec in data:
        all_records.extend(rec['battingSummary']) # appned these arrays.
df_batting = pd.DataFrame(all_records)
df_batting.head(11)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/â€ Mendis),44,28,4,0,157.14
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c â€ Mendis b Theekshana,0,1,0,0,0.00
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,c â€ Green b Wiese,6,6,0,0,100.00
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,c Shikongo b Frylinck,12,11,1,0,109.09

In [9]:
df_batting["out/not_out"] = df_batting.dismissal.apply(lambda x: "out" if len(x)>0 else "not_out")
df_batting.head(15)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/â€ Mendis),44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c â€ Mendis b Theekshana,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,c â€ Green b Wiese,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,c Shikongo b Frylinck,12,11,1,0,109.09,out
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,c â€ Green b Shikongo,0,1,0,0,0.00,out
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,c la Cock b Scholtz,20,21,2,0,95.23,out
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),c â€ Green b Frylinck,29,23,2,1,126.08,out
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,c Loftie-Eaton b Scholtz,4,8,0,0,50.00,out

In [10]:
df_batting.drop(columns=['dismissal'], inplace = True)
df_batting.head(15)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,out
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,0,1,0,0,0.00,out
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,20,21,2,0,95.23,out
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),29,23,2,1,126.08,out
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,4,8,0,0,50.00,out

In [11]:
df_batting["batsmanName"] = df_batting['batsmanName'].apply(lambda x: x.replace('â€', ''))
df_batting["batsmanName"] = df_batting['batsmanName'].apply(lambda x: x.replace('\xa0', ''))
df_batting.head(15)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,out
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,0,1,0,0,0.00,out
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,20,21,2,0,95.23,out
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),29,23,2,1,126.08,out
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,4,8,0,0,50.00,out

In [12]:
df_batting['match_id'] = df_batting['match'].map(match_ids_dict)
df_batting.head()

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out,match_id
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out,T20I # 1823
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out,T20I # 1823
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out,T20I # 1823
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out,T20I # 1823
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out,T20I # 1823

In [13]:
df_batting.to_csv("t20_csv_files/fact_bating_score.csv",index = False)

Process Bowling Data

In [14]:
with open(r"D:\Deepak_Work\Our Goal is Google\Cricket_data_analysis\t20_json_files\t20_json_files\t20_wc_bowling_summary.json") as f:
    data = json.load(f)
        
    all_records = []
    for rec in data:
        all_records.extend(rec['bowlingSummary']) # appned these arrays.
df_bowling = pd.DataFrame(all_records)
df_bowling.head(11)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0
5,Namibia Vs Sri Lanka,Namibia,Gerhard Erasmus,1,0,8,0,8.00,1,1,0,0,0
6,Namibia Vs Sri Lanka,Namibia,David Wiese,4,0,16,2,4.00,13,1,0,0,0
7,Namibia Vs Sri Lanka,Namibia,Bernard Scholtz,4,0,18,2,4.50,10,1,0,0,0
8,Namibia Vs Sri Lanka,Namibia,Ben Shikongo,3,1,22,2,7.33,6,3,0,0,0
9,Namibia Vs Sri Lanka,Namibia,JJ Smit,3,0,16,1,5.33,7,0,0,1,0
10,Namibia Vs Sri Lanka,Namibia,Jan Frylinck,4,0,26,2,6.50,10,0,2,1,0

In [15]:
df_bowling.shape # To check how many rows and columns are persent in our file.

(500, 13)

In [16]:
df_bowling['match_id'] = df_bowling['match'].map(match_ids_dict)
df_bowling.head()

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,match_id
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0,T20I # 1823
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0,T20I # 1823
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0,T20I # 1823
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0,T20I # 1823
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0,T20I # 1823

In [17]:
df_bowling.to_csv('t20_csv_files/fact_bowling_data.csv', index = False)

Process Player Information

In [18]:
with open(r"D:\Deepak_Work\Our Goal is Google\Cricket_data_analysis\t20_json_files\t20_json_files\t20_wc_player_info.json") as f:
    data = json.load(f)   
df_players = pd.DataFrame(data)
print(df_players.shape) 
df_players.head(11)

(219, 6)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus(c),Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
5,Jan Frylinck,Namibia,Left hand Bat,Left arm Fast medium,Allrounder,
6,David Wiese,Namibia,Right hand Bat,Right arm Medium fast,Allrounder,David Wiese joined a marked outflow of South A...
7,JJ Smit,Namibia,Right hand Bat,Left arm Medium fast,Bowling Allrounder,
8,Pathum Nissanka,Sri Lanka,Right hand Bat,,Top order Batter,
9,Kusal Mendisâ€,Sri Lanka,Right hand Bat,Legbreak,Wicketkeeper Batter,"Blessed with a compact technique, an aggressiv..."
10,Dhananjaya de Silva,Sri Lanka,Right hand Bat,Right arm Offbreak,Allrounder,A technically correct top-order batsman from t...

In [19]:
df_players['name'] = df_players['name'].apply(lambda x: x.replace('â€',''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('t',''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('\xa0',''))
df_players.head(15)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Lofie-Eaon,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Sephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus(c),Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
5,Jan Frylinck,Namibia,Left hand Bat,Left arm Fast medium,Allrounder,
6,David Wiese,Namibia,Right hand Bat,Right arm Medium fast,Allrounder,David Wiese joined a marked outflow of South A...
7,JJ Smi,Namibia,Right hand Bat,Left arm Medium fast,Bowling Allrounder,
8,Pahum Nissanka,Sri Lanka,Right hand Bat,,Top order Batter,
9,Kusal Mendis,Sri Lanka,Right hand Bat,Legbreak,Wicketkeeper Batter,"Blessed with a compact technique, an aggressiv..."
10,Dhananjaya de Silva,Sri Lanka,Right hand Bat,Right arm Offbreak,Allrounder,A technically correct top-order batsman from t...
11,Danushka Gunahilaka,Sri Lanka,Left hand Bat,Right arm Offbreak,Allrounder,"A poised, attacking left-handed opener groomed..."
12,Bhanuka Rajapaksa,Sri Lanka,Left hand Bat,Right arm Medium,Top order Batter,"An attacking left-handed batsman, Bhanuka Raja..."
13,Dasun Shanaka(c),Sri Lanka,Right hand Bat,Right arm Medium,Allrounder,"An explosive middle-order batsman, and steady ..."
14,Wanindu Hasaranga de Silva,Sri Lanka,Right hand Bat,Legbreak,Allrounder,"A bruising lower-middle order batsman, and an ..."

In [20]:
df_players[df_players['team'] == 'India']

,name,team,battingStyle,bowlingStyle,playingRole,description
127,KL Rahul,India,Right hand Bat,,Opening Batter,"A tall, elegant right-hand batsman who can kee..."
128,Rohi Sharma(c),India,Right hand Bat,Right arm Offbreak,Top order Batter,"Languid and easy on the eye, Rohit Sharma owne..."
129,Vira Kohli,India,Right hand Bat,Right arm Medium,Top order Batter,India has given to the world many a great cric...
130,Suryakumar Yadav,India,Right hand Bat,"Right arm Medium, Right arm Offbreak",Batter,Hard-hitting 360-degree batter Suryakumar Yada...
131,Axar Pael,India,Left hand Bat,Slow Left arm Orthodox,Bowling Allrounder,Left-arm spinner Axar Patel has been increasin...
132,Hardik Pandya,India,Right hand Bat,Right arm Medium fast,Allrounder,Hardik Pandya swears by living life king size ...
133,Dinesh Karhik,India,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Not many would forget the sight of Dinesh Kart...
134,Ravichandran Ashwin,India,Right hand Bat,Right arm Offbreak,Bowling Allrounder,R Ashwin took the tricks and skills he learned...
135,Bhuvneshwar Kumar,India,Right hand Bat,Right arm Medium,Bowler,"At the time of his India debut in 2012, Bhuvne..."
136,Arshdeep Singh,India,Left hand Bat,Left arm Medium fast,Bowler,
137,Mohammed Shami,India,Right hand Bat,Right arm Fast,Bowler,Mohammed Shami was India's leading fast bowler...
192,Deepak Hooda,India,Right hand Bat,Right arm Offbreak,Allrounder,"An allrounder who can bat in any position, Dee..."
211,Rishabh Pan,India,Left hand Bat,,Wicketkeeper Batter,"A match-turning, swashbuckling batter-keeper i..."

In [21]:
df_players.to_csv('t20_csv_files/dim_players_no_images.csv', index = False)